export const INITIAL_CAPITAL_DEFAULT = 500_000;
export const INITIAL_CAPITAL_MIN = 100_000;
export const INITIAL_CAPITAL_MAX = 10_000_000;
export const INITIAL_CAPITAL_STEP = 100_000;

export const INVESTMENT_DURATION_DEFAULT = 2;
export const INVESTMENT_DURATION_MIN = 1;
export const INVESTMENT_DURATIN_MAX = 50;
export const INVESTMENT_DURATION_STEP = 1;

export const ANNUAL_GAIN_EXPECTATION_DEFAULT = 7;
export const ANNUAL_GAIN_EXPECTATION_MIN = 1;
export const ANNUAL_GAIN_EXPECTATION_MAX = 100;
export const ANNUAL_GAIN_EXPECTATION_STEP = 1;

export const W_M_AND_PROD_FEES_DEFAULT = 2.0;
export const W_M_AND_PROD_FEES_MIN = 1.0;
export const W_M_AND_PROD_FEES_MAX = 10.0;
export const W_M_AND_PROD_FEES_STEP = 0.1;
